# Generated by Django 2.2.3 on 2020-01-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='college',
        ),
    ]
