# Generated by Django 2.2.3 on 2020-01-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0004_remove_alumni_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sih_app.College'),
        ),
    ]
