# Generated by Django 2.2.3 on 2020-01-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0006_college_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='password',
        ),
        migrations.RemoveField(
            model_name='college',
            name='value',
        ),
        migrations.AddField(
            model_name='alumni',
            name='end_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='start_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sih_app.Course'),
        ),
    ]
