# Generated by Django 2.2.3 on 2020-01-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0007_auto_20200111_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='birth_date',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='dp',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='alumni',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
