# Generated by Django 2.2.3 on 2020-01-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0008_auto_20200111_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='score',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
