# Generated by Django 2.2.3 on 2020-01-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0009_auto_20200111_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='course',
            field=models.ManyToManyField(to='sih_app.Course'),
        ),
    ]
