# Generated by Django 2.2.3 on 2020-01-11 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0010_college_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='alumni',
            name='dp',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
