# Generated by Django 2.2.3 on 2020-01-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0011_auto_20200112_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_from', models.DateField(null=True)),
                ('date_to', models.DateField(null=True)),
                ('t1', models.TimeField(null=True)),
                ('t2', models.TimeField(null=True)),
                ('pic', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='notices',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notices',
            name='pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notices',
            name='notice',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
